import { Geist, Geist_Mono, Mulish } from "next/font/google";
import "./globals.css";

import Navbar from "@/lib/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${mulish.variable} antialiased  font-mulish w-full flex relative max-lg:flex-col `}>
        {children}
        <Navbar />
      </body>
    </html>
  );
}
